### ISSUE TITLE
Clarification request

### ISSUE THREAD

**Issue by MikePall** [mkeeter/ssra#1]
This *is* the LuaJIT register allocator. Period.

Code published 2009. Description published here: https://lua-users.org/lists/lua-l/2009-11/msg00089.html (ignore the TLS cert error).

Coming up with a silly markting name, writing a naive implementation and then claiming it's your invention is impertinent. Especially since you mention LuaJIT itself in the text ...

I suggest you clarify this here, too, as discussed over at https://news.ycombinator.com/item?id=33080799.

**Comment by mkeeter** [comment]
Done in 43611c92692e27689c26b5390048af956a2689ae
